// =====================================================
// Tactile Forge Arcade · Self-host Google Fonts in a game
//   node tools/selfhost-fonts.mjs <gameDir>
//
// Finds every Google Fonts stylesheet a game loads (<link> in HTML, @import in
// CSS), downloads the Latin and Latin-Extended WOFF2 files plus each family's
// licence into <gameDir>/fonts/, writes fonts/fonts.css, and rewrites the
// references to point at it. Afterwards the game makes no request to Google.
// Run it on a clean git checkout and review the diff before committing.
// =====================================================

import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, relative, dirname, sep, resolve } from 'node:path';

const GAME = resolve(process.argv[2] || '.');
const FONTS = join(GAME, 'fonts');
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/147.0 Safari/537.36';
const KEEP_SUBSETS = new Set(['latin', 'latin-ext']);
const SKIP_DIRS = new Set(['node_modules', '.git', 'tools', 'docs', 'test', 'tests', 'fonts']);

async function walk(dir) {
  const out = [];
  for (const e of await readdir(dir, { withFileTypes: true })) {
    if (e.isDirectory()) { if (!SKIP_DIRS.has(e.name)) out.push(...await walk(join(dir, e.name))); }
    else if (/\.(html|css)$/i.test(e.name)) out.push(join(dir, e.name));
  }
  return out;
}

const GF_URL = /https:\/\/fonts\.googleapis\.com\/css2?\?[^"')\s]+/g;
const files = await walk(GAME);
const sources = new Map();           // file -> text
const urls = new Set();
for (const f of files) {
  const text = await readFile(f, 'utf8');
  const found = text.match(GF_URL);
  if (found || /fonts\.(googleapis|gstatic)\.com/.test(text)) sources.set(f, text);
  for (const u of found || []) urls.add(u.replace(/&amp;/g, '&'));
}
if (!urls.size) { console.log('No Google Fonts references found — nothing to do.'); process.exit(0); }

await mkdir(FONTS, { recursive: true });
const faces = new Map();             // dedupe key -> @font-face text
const families = new Set();
const downloaded = new Map();        // remote url -> local file name

for (const u of urls) {
  const res = await fetch(u, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`fetch ${u}: ${res.status}`);
  const css = await res.text();
  // Google's css2 output: "/* subset */\n@font-face { ... }"
  for (const m of css.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*(@font-face\s*\{[^}]*\})/g)) {
    const [, subset, block] = m;
    if (!KEEP_SUBSETS.has(subset)) continue;
    const family = block.match(/font-family:\s*'([^']+)'/)[1];
    const weight = (block.match(/font-weight:\s*([^;]+);/) || [, '400'])[1].trim();
    const style  = (block.match(/font-style:\s*([^;]+);/)  || [, 'normal'])[1].trim();
    const src    = block.match(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/)[1];
    families.add(family);
    let local = downloaded.get(src);
    if (!local) {
      const slug = family.toLowerCase().replace(/[^a-z0-9]+/g, '-');
      local = `${slug}-${createHash('sha1').update(src).digest('hex').slice(0, 8)}.woff2`;
      const buf = Buffer.from(await (await fetch(src)).arrayBuffer());
      await writeFile(join(FONTS, local), buf);
      downloaded.set(src, local);
    }
    const key = `${family}|${weight}|${style}|${subset}`;
    faces.set(key, `/* ${family} ${weight} ${style} — ${subset} */\n` +
      block.replace(src, `./${local}`).replace(/url\(\.\/[^)]+\)/, `url('./${local}')`));
  }
}

await writeFile(join(FONTS, 'fonts.css'),
  '/* Self-hosted copies of Google Fonts (SIL OFL / Apache licences in this folder).\n' +
  '   Generated by tactile-forge-arcade/tools/selfhost-fonts.mjs — no request leaves the site. */\n\n' +
  [...faces.values()].join('\n\n') + '\n');

// Licences: Google Fonts keeps each family's licence in its GitHub repo.
const missingLicence = [];
for (const family of families) {
  const slug = family.toLowerCase().replace(/[^a-z0-9]/g, '');
  let got = false;
  for (const [dir, file] of [['ofl', 'OFL.txt'], ['apache', 'LICENSE.txt'], ['ufl', 'UFL.txt']]) {
    const r = await fetch(`https://raw.githubusercontent.com/google/fonts/main/${dir}/${slug}/${file}`);
    if (r.ok) { await writeFile(join(FONTS, `LICENSE-${slug}.txt`), await r.text()); got = true; break; }
  }
  if (!got) missingLicence.push(family);
}

// Rewrite references.
let edits = 0;
for (const [f, text] of sources) {
  const rel = relative(dirname(f), join(FONTS, 'fonts.css')).split(sep).join('/');
  let out = text
    // preconnect hints to Google are no longer needed
    .replace(/^[ \t]*<link[^>]+href=["']https:\/\/fonts\.(googleapis|gstatic)\.com\/?["'][^>]*>[ \t]*\r?\n/gm, '')
    .replace(/(<link[^>]+href=["'])https:\/\/fonts\.googleapis\.com\/css2?\?[^"']+(["'])/g, `$1${rel}$2`)
    .replace(/@import\s+url\(\s*["']?https:\/\/fonts\.googleapis\.com\/css2?\?[^"')]+["']?\s*\)\s*;?/g, `@import url('${rel}');`);
  if (out !== text) { await writeFile(f, out); edits++; }
}

// Anything left pointing at Google is a failure.
const leftovers = [];
for (const f of await walk(GAME)) {
  const t = await readFile(f, 'utf8');
  if (/fonts\.(googleapis|gstatic)\.com/.test(t)) leftovers.push(relative(GAME, f));
}
console.log(`fonts: ${families.size} families (${[...families].join(', ')}), ` +
  `${downloaded.size} WOFF2 files, ${faces.size} @font-face rules, ${edits} files rewritten`);
if (missingLicence.length) console.log(`WARN — no licence found for: ${missingLicence.join(', ')}`);
if (leftovers.length) { console.error(`FAIL — still references Google Fonts: ${leftovers.join(', ')}`); process.exit(1); }
